### ISSUE TITLE
Using configure + make then being able to run the program

### ISSUE THREAD

**Issue by Aethelflaed** [Jacques-Olivier/VisualBoyAdvance_Link#1]
I just cloned your project and I'm quite surprised as to how I should use it.

I must run a command as root, but why ?

The application sounds promising, but I'm still trying to make it work :/ (Currently stuck with some java errors)

Is it possible to create a clean source repo with optional packaging targets in the Makefile ?

**Comment by Jacques-Olivier** [comment]
Hi. 

Root user is used to setup applications in directories that only super isers as root can access.

What are the Java errors ? For informations, only 32-bit system is supported. I haven't tested my application on 64-bit systems.

The Makefile doesn't have issue for me if you have dependencies installed in your OS thanks to cmake that checks if all required libraries are installed (I didn't verify if Java is present if you use special versions)

**Comment by Aethelflaed** [comment]
I actually had to install a 32 bits java and update the launcher to be able to launch the game. I also had some interfaces problems because my windows are not floating by default, but I managed to make it work.

**Comment by Jacques-Olivier** [comment]
Great it works for you now. I think that I will apply some changes in the code (Java GUI) : I have issues with Eclipse and some of his plugins. The next version will have a better GUI version. For now, it's time for me to begin these modifications ^^

**Comment by Aethelflaed** [comment]
I have some problem with Java GUIs, I really don't like them but that's not the point :)

Whenever I have some time, I'll take a look at the code, if you keep it up-to-date !
